
#1-Generate a sample by equation


> *y=w1X1+w2X2+....+b*





#2-Generate random number for Xs

#3-Apply Linear Regression

#4-Proof the same equatio will return using generated sample datasets



In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import norm
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import datasets
import matplotlib.pyplot as plt
from random import sample
from numpy.linalg import inv, det

In [ ]:
#assumptions for W
W1=4
W2=8
W3=15
b=1

In [ ]:
#generate random X
X1 = np.random.randint(0, 100, size = 100)#generate random array from 0 to 100
X1_t=np.transpose([X1])
X2 = np.random.randint(0, 100, size = 100)#generate random array from 0 to 100
X2_t=np.transpose([X2])
X3= np.random.randint(0, 100, size = 2)#generate random array from 0 to 100
X3_t=np.transpose([X3])
print(X1_t)
print(X2_t)
print(X3_t)

[[ 9]
 [39]
 [60]
 [13]
 [83]
 [94]
 [55]
 [33]
 [84]
 [45]
 [55]
 [61]
 [55]
 [50]
 [60]
 [53]
 [81]
 [38]
 [86]
 [47]
 [85]
 [27]
 [ 3]
 [46]
 [57]
 [61]
 [92]
 [24]
 [87]
 [70]
 [10]
 [ 0]
 [71]
 [19]
 [85]
 [21]
 [54]
 [32]
 [95]
 [89]
 [39]
 [90]
 [29]
 [22]
 [35]
 [63]
 [79]
 [37]
 [28]
 [52]
 [ 9]
 [92]
 [56]
 [48]
 [62]
 [43]
 [65]
 [18]
 [38]
 [36]
 [68]
 [95]
 [84]
 [23]
 [25]
 [85]
 [44]
 [46]
 [20]
 [15]
 [15]
 [29]
 [80]
 [59]
 [41]
 [66]
 [71]
 [ 5]
 [29]
 [66]
 [17]
 [ 2]
 [ 0]
 [42]
 [39]
 [25]
 [94]
 [74]
 [32]
 [30]
 [47]
 [39]
 [91]
 [41]
 [30]
 [54]
 [65]
 [40]
 [59]
 [97]]
[[ 4]
 [55]
 [26]
 [44]
 [52]
 [82]
 [15]
 [14]
 [93]
 [70]
 [75]
 [77]
 [28]
 [46]
 [93]
 [90]
 [89]
 [21]
 [90]
 [54]
 [72]
 [29]
 [84]
 [98]
 [81]
 [62]
 [ 6]
 [39]
 [92]
 [75]
 [16]
 [28]
 [96]
 [21]
 [69]
 [22]
 [64]
 [71]
 [60]
 [48]
 [60]
 [95]
 [27]
 [ 6]
 [69]
 [ 2]
 [62]
 [48]
 [89]
 [88]
 [94]
 [21]
 [26]
 [71]
 [11]
 [16]
 [47]
 [87]
 [25]
 [89]
 [26]
 [26]
 [77]
 [76]
 [20]
 [94]
 [4

In [ ]:
#for 2d
Y=W1*X1 + W2*X2+b
num_of_samples=100
B = np.ones(num_of_samples, dtype = int)
B_t=np.transpose([B])
z=np.array([X1,X2])
X=np.hstack((B_t,np.transpose(z)))
X_t=np.transpose(X)
o=np.dot(X_t,X)
inverse=np.linalg.inv(o)
s = np.dot(inverse,X_t)
WN=np.dot(s,Y)
WN

array([1., 4., 8.])

In [ ]:
#for 1D
X11 = np.random.randint(0, 100)
Ye=(W1*np.transpose(X11))+b
W1*np.transpose(X11)
W_d=pow((X11*X11),-1)*np.transpose(X11)*Ye
W_d

4.047619047619048

##Refrences

https://machinelearningmastery.com/linear-regression-for-machine-learning/

https://towardsdatascience.com/linear-regression-derivation-d362ea3884c2

